### ISSUE TITLE
Review EPSG:3857 WMS layers

### ISSUE THREAD

**Issue by tyrasd** [osmlab/editor-layer-index#425]
Here's a list of all WMS layers currently in the index that claim to support the spherical mercator projection (EPSG:3857 or one of its alternative codes) and would be affected in https://github.com/openstreetmap/iD/pull/4814.

I've run a small [script](https://gist.github.com/tyrasd/d35ae4df5cf387aba50743174d733cee) to test whether the respective services actually return a valid response for the advertised features. For this I've executed 100 random WMS requests (random points in the layer's polygon) for each layer and _available_projection_. If a non-error HTTP response with an _image_ HTTP content-type header is returned, that's called a success (would be better to also look into the response image and see if it actually contains some data and not just a white, black or transparent background). Otherwise the script does a bit of magic to try to find out why the request couldn't be loaded. Here's the cases I found:

### EPSG:3857 services

* :globe_with_meridians: something to do with the coordinate reference system ("projection", "SRS")
* :file_folder: probably a layer doesn't exist on the server anymore
* :computer: server returned an HTTP error (e.g. 404 page not found, 500 internal server error, …)
* :clock1: request timed out
* :question: other

Here are the results (raw data incl. actual request logs in [this gist](https://gist.github.com/tyrasd/3b9536fd3ca51cbd67c4ff0d905c1730)):

* [x] LPI_NSW_Administrative_Boundaries_County	EPSG:3857									:file_folder: → https://github.com/osmlab/editor-layer-index/pull/118#issuecomment-368329013
* [x] LPI_NSW_Administrative_Boundaries_LGA	EPSG:3857									:file_folder: → https://github.com/osmlab/editor-layer-index/pull/118#issuecomment-368329013
* [x] LPI_NSW_Administrative_Boundaries_NPWS_Reserve	EPSG:3857									:file_folder: → https://github.com/osmlab/editor-layer-index/pull/118#issuecomment-368329013
* [x] LPI_NSW_Administrative_Boundaries_Parish	EPSG:3857									:file_folder: → https://github.com/osmlab/editor-layer-index/pull/118#issuecomment-368329013
* [x] LPI_NSW_Administrative_Boundaries_StateForest	EPSG:3857									:file_folder: → https://github.com/osmlab/editor-layer-index/pull/118#issuecomment-368329013
* [x] LPI_NSW_Administrative_Boundaries_Suburb	EPSG:3857									:file_folder: → https://github.com/osmlab/editor-layer-index/pull/118#issuecomment-368329013
* [x] geoimage.at	EPSG:3857									
* [x] geoimage.at	EPSG:900913									
* [x] graz.at-basemap	EPSG:3857									:computer: → https://twitter.com/tyr_asd/status/967831295555506176 → b0e9fbeb8358282e73a0f9d9a24aec62428dd2d0
* [x] tirol.gv.at-contourlines	EPSG:3857									
* [x] tirol.gv.at-contourlines	EPSG:102100									
* [x] tirol.gv.at-DGM	EPSG:3857									
* [x] tirol.gv.at-DGM	EPSG:102100									
* [x] tirol.gv.at-DOM	EPSG:3857									
* [x] tirol.gv.at-DOM	EPSG:102100									
* [x] tirol.gv.at-orthofoto	EPSG:3857									
* [x] tirol.gv.at-orthofoto	EPSG:102100									
* [x] tirol.gv.at-orthofoto-cir	EPSG:3857									
* [x] tirol.gv.at-orthofoto-cir	EPSG:102100									
* [x] vogis.cnv.at-DGM	EPSG:3785									:globe_with_meridians: → 8838989
* [x] vogis.cnv.at-DGM	EPSG:3857									
* [x] vogis.cnv.at-DGM	EPSG:900913									:question: → 8838989
* [x] vogis.cnv.at-DOM	EPSG:3785									:globe_with_meridians: → 8838989
* [x] vogis.cnv.at-DOM	EPSG:3857									
* [x] vogis.cnv.at-DOM	EPSG:900913									:question: → 8838989
* [x] vogis.cnv.at-ef2012_12cm	EPSG:3785									:globe_with_meridians: → 8838989
* [x] vogis.cnv.at-ef2012_12cm	EPSG:3857									
* [x] vogis.cnv.at-ef2012_12cm	EPSG:900913									:question: → 8838989
* [x] vogis.cnv.at-ef2015_10cm	EPSG:3785									:globe_with_meridians: → 8838989
* [x] vogis.cnv.at-ef2015_10cm	EPSG:3857									
* [x] vogis.cnv.at-ef2015_10cm	EPSG:900913									:question: → 8838989
* [x] vogis.cnv.at-wi2015_20cm	EPSG:3785									:globe_with_meridians: → 8838989
* [x] vogis.cnv.at-wi2015_20cm	EPSG:3857									
* [x] vogis.cnv.at-wi2015_20cm	EPSG:900913									:question: → 8838989
* [x] AGIV10cm	EPSG:3857									
* [x] AGIV10cm	EPSG:102100									
* [x] UrbISOrtho2016	EPSG:3857									
* [x] UrbisAdmFR	EPSG:3857									
* [x] UrbisAdmNL	EPSG:3857									
* [x] Czech_CUZK-KM	EPSG:3857									
* [x] Czech_CUZK-KM	EPSG:900913									
* [x] hamburg-40cm	EPSG:3857									:question: → 3a2be47
* [x] hamburg-40cm	EPSG:102100									:question: → 3a2be47
* [x] GEOSN-DOP-RGB	EPSG:3857									
* [x] Catastro-Spain	EPSG:3785									
* [x] Catastro-Spain	EPSG:3857									
* [x] Toulouse-Orthophotoplan-2007	EPSG:3857									
* [x] Toulouse-Orthophotoplan-2007	EPSG:900913									
* [x] Toulouse-Orthophotoplan-2011	EPSG:3857									
* [x] Toulouse-Orthophotoplan-2011	EPSG:900913									
* [x] Toulouse-Orthophotoplan-2013	EPSG:3857									
* [x] Toulouse-Orthophotoplan-2013	EPSG:900913									
* [x] Toulouse-Orthophotoplan-2015	EPSG:3857									
* [x] Toulouse-Orthophotoplan-2015	EPSG:900913									
* [x] Budapest_XI_2015	EPSG:900913									
* [x] Budapest_XI_2017	EPSG:900913									
* [x] Torokbalint-orthophoto-2013	EPSG:900913									:globe_with_meridians: → 5eb9eea
* [x] Torokbalint-orthophoto-2013	EPSG:3857									
* [x] Torokbalint-orthophoto-2015	EPSG:900913									:globe_with_meridians: → 5eb9eea
* [x] Torokbalint-orthophoto-2015	EPSG:3857									
* [x] PCN-Italy-2006	EPSG:3857									
* [x] South-Tyrol-Orthofoto2011-20cm	EPSG:3857									
* [x] Canvec	EPSG:900913									
* [x] Geobase_Hydrography	EPSG:900913									
* [x] Geobase_Roads	EPSG:900913									
* [x] geodata.md.gov-MD_ThreeInchImagery	EPSG:3857									
* [x] NC-US	EPSG:3857									
* [x] NC-US	EPSG:102100									
* [x] orthos.dhses.ny.gov_latest	EPSG:3857									
* [x] Philadelphia2015Imagery	EPSG:3857									:computer: → https://github.com/osmlab/editor-layer-index/issues/218#issuecomment-368331255 → 8e8f7e7
* [x] arapiraca_al	EPSG:3857									
* [x] branquinha_al	EPSG:3857									
* [x] cajueiro_al	EPSG:3857									
* [x] campo_alegre_al	EPSG:3857									
* [x] capela_al	EPSG:3857									
* [x] delmiro_gouveia	EPSG:3857									
* [x] estrela_de_alagoas	EPSG:3857									
* [x] girau_do_pnciano	EPSG:3857									
* [x] major_isidoro	EPSG:3857									
* [x] mar_vermelho_al	EPSG:3857									
* [x] minador_do_negrao	EPSG:3857									
* [x] olho_dagua_do_casado	EPSG:3857									
* [x] al_palestina	EPSG:3857									
* [x] palmeira_dos_indios	EPSG:3857									
* [x] pao_de_acucar	EPSG:3857									
* [x] al_piranhas	EPSG:3857									
* [x] poco_das_trincheiras	EPSG:3857									
* [x] santana_do_ipanema	EPSG:3857									
* [x] Sao_miguel_dos_campos	EPSG:3857									
* [x] teotonio_vilela	EPSG:3857									
* [x] uniao_dos_palmares	EPSG:3857									
* [x] vicosa_al	EPSG:3857									
* [x] alagoas_litoral	EPSG:3857									
* [x] der-es	EPSG:3857									
* [x] IBGE_BC250_Aglomerado_Rural	EPSG:3857									
* [x] IBGE_BC250_Pista_Pouso	EPSG:3857									
* [x] IBGE_BC250_Rios_Drenagem	EPSG:3857									
* [x] IBGE_BC250_Rodoviario	EPSG:3857									
* [x] IBGE_BC250_Terra_Indegina	EPSG:3857									
* [x] IBGE_BC250_Terra_Publico_Militar	EPSG:3857									:globe_with_meridians: → https://github.com/osmlab/editor-layer-index/pull/318#issuecomment-368330635
* [x] IBGE_BC250_Uso_Sustentavel	EPSG:3857									
* [x] IBGE_BC250_Villa	EPSG:3857									
* [x] IBGE_BCIM_Gerador_Eletrica	EPSG:3857									
* [x] IBGE_BCIM_Municipio	EPSG:3857									
* [x] sc2012	EPSG:102113									
* [x] sc2012	EPSG:3587									:question: → https://github.com/osmlab/editor-layer-index/commit/3e626443cd1cf6e579c6f6a20ea8aae1c885a0e7#r27777122
* [x] sc2012	EPSG:3785									
* [x] sc2012	EPSG:3857									
* [x] sc2012	EPSG:41001									
* [x] sc2012	EPSG:54004									
* [x] sc2012	EPSG:900913									
* [x] landsat	EPSG:3857									:clock1: → [josm.osm.de#15940](https://josm.openstreetmap.de/ticket/15940) → 6186b65
* [x] landsat	EPSG:3785									:clock1: → [josm.osm.de#15940](https://josm.openstreetmap.de/ticket/15940) → 6186b65
* [x] landsat	EPSG:900913									:clock1: → [josm.osm.de#15940](https://josm.openstreetmap.de/ticket/15940) → 6186b65

### non EPSG:3857 services

Here's a similar list of all WMS services that according to this editor-layer-index don't offer `EPSG:3857` (either because they have the `available_projections` field not set, or don't have `EPSG:3857` in there), see https://github.com/osmlab/editor-layer-index/issues/425#issuecomment-368602446 below: An :shipit: means that the repective layer returns data when requesting EPSG:3857 tiles, even though it "shouldn't"; all other symbols have the same meaning as above (the "expected" case would actually be an SRS-related error message represented by :globe_with_meridians:).

* [x] Fribourg-2005	EPSG:3857 :computer:
* [x] Geneve-SITG-2011	EPSG:3857 :shipit:
* [x] Neuchatel-SITN-2006	EPSG:3857 :computer:
* [x] Jura-RCJU-1998	EPSG:3857	:computer:
* [x] Yverdon_les_Bains-HEIG_VD-2007	EPSG:3857	(~:shipit:~) //edit: :computer: ?
* [x] Solothurn-sogis2014-wms	EPSG:3857	:globe_with_meridians: :white_check_mark:
* [x] Solothurn-infrared-SOGIS	EPSG:3857	:globe_with_meridians: :white_check_mark:
* [x] Bern-bern2016-wms	EPSG:3857	:computer: → https://github.com/osmlab/editor-layer-index/pull/197#issuecomment-370532884 → :globe_with_meridians: :white_check_mark:
* [x] bavaria-2m	EPSG:3857	(~:shipit:~) //edit: false positive, actually :globe_with_meridians: :white_check_mark:
* [x] Erlangen-2013	EPSG:3857	:shipit:
* [x] Erlangen-2011	EPSG:3857	:shipit:
* [x] Erlangen-2016	EPSG:3857	:shipit:
* [x] Hamburg-DK5	EPSG:3857	(~:shipit:~) //edit: false positive, actually :globe_with_meridians: :white_check_mark:
* [x] maaamet.ee-pohi_vr2	EPSG:3857	:globe_with_meridians: :white_check_mark:
* [x] maaamet.ee-cir_ngr	EPSG:3857	:globe_with_meridians: :white_check_mark:
* [x] maaamet.ee-reljeef	EPSG:3857	:globe_with_meridians: :white_check_mark:
* [x] maaamet.ee-of10000	EPSG:3857	:globe_with_meridians: :white_check_mark:
* [x] GRAFCAN-Canary_Islands	EPSG:3857	:globe_with_meridians: :white_check_mark:
* [x] IDEIB-Balearic_Islands	EPSG:3857	:computer:
* [x] ITACyL-Castile-and-Leon	EPSG:3857	:globe_with_meridians: :white_check_mark:
* [x] PNOA-Spain	EPSG:3857	:shipit:
* [x] SIGPAC-Spain	EPSG:3857	:computer:
* [x] CRAIG-Auvergne-2016_mirror1	EPSG:3857	:shipit:
* [x] Geolittoral-Orthophotos2000	EPSG:3857	:shipit:
* [x] Geolittoral-Sentiers	EPSG:3857	:shipit:
* [x] GeolittoralV2-Orthophotos	EPSG:3857	:shipit:
* [x] Geobretagne-Brest-2010	EPSG:3857	:computer:
* [x] Geobretagne-Morbihan-2010	EPSG:3857	:computer:
* [x] Budapest_XI_2015	EPSG:3857	:globe_with_meridians: :white_check_mark:
* [x] Budapest_XI_2017	EPSG:3857	:globe_with_meridians: :white_check_mark:
* [x] Lodi-Italy	EPSG:3857	:computer:
* [x] Lombardia-Italy-CTR	EPSG:3857	:shipit:
* [x] Lombardia-Italy-CTR-DBT	EPSG:3857	:shipit:
* [x] PCN-Lazio_Umbria-2008	EPSG:3857	:shipit:
* [x] Sicily-ATA2007	EPSG:3857	:shipit:
* [x] Latvia-ortho-Coastline-20cm	EPSG:3857	:computer:
* [x] Latvia-ortho-50cm	EPSG:3857	:computer:
* [x] USSR-Latvia	EPSG:3857	:shipit:
* [x] Canvec	EPSG:3857	:shipit:
* [x] Geobase_Hydrography	EPSG:3857	:shipit:
* [x] Geobase_Roads	EPSG:3857	:shipit:
* [x] MSR_Maps-Topo	EPSG:3857	:question:
* [x] MSR_Maps-Urban	EPSG:3857	:question:
* [x] rio2013	EPSG:3857	:shipit:
* [x] rio2015	EPSG:3857	:shipit:

**Comment by Klumbumbus** [comment]
Regarding Landsat, see https://josm.openstreetmap.de/ticket/15940

**Comment by simonpoole** [comment]
I was discussing with @grischard in Karlsruhe last week that what we are missing in general, not just for WMS, is checking if the layers actually work both JOSM and ELI are accumulating old stuff that long stopped working, not to mention simple URL changes and so on. Any chance this could be included in the repo and run regularly (not on every build but perhaps once per week or so)?

**Comment by tyrasd** [comment]
> Any chance this could be included in the repo and run regularly (not on every build but perhaps once per week or so)?

Sure. Let me see what I can do…

**Comment by bhousel** [comment]
This is so awesome, thanks @tyrasd for coordinating all this work 🙇

**Comment by grischard** [comment]
@tyrasd would it please be possible to run your script on the wms servers that _don't_ advertise EPSG:(3857|900913|3587|54004|41001|102113|102100|3785) to see if they secretly do?

[There's a list here](https://github.com/osmlab/editor-layer-index/commit/c2de955bdcf06f308dd37d4bd5938e5dde744a75#commitcomment-27643943).

**Comment by tyrasd** [comment]
Done (see _non EPSG:3857 services_ section above). I went ahead and tested all 45 layers that according to eli don't seem to support web mercator (including ones without the `available_projections` field set).

**Comment by grischard** [comment]
So that's 22 extra layers if I'm counting right? That's fantastic!

**Comment by Marc-marc-marc** [comment]
could these tests be performed regularly?  for example once a week if the previous test succeeds and once a day if recent error. it would help identify future problems.
could the test results be published on a web page or in the repository ? this would allow for action to be taken accordingly and/or prevent each project from making a tester.

**Comment by tyrasd** [comment]
> could these tests be performed regularly?

yes, @Marc-marc-marc (see my comment above https://github.com/osmlab/editor-layer-index/issues/425#issuecomment-368337749) – I'm just still experimenting with different ways to get it done.

> could the test results be published on a web page or in the repository ?

good idea, it would be nice to have a github bot, reporting persistent problems (e.g. when a layer is not functional for more than a week or two).

**Comment by grischard** [comment]
What we're thinking about here is some kind of monitoring. Wouldn't a github bot have to run somewhere, and run only on commits? We could also run this daily by using a [Travis cron job](https://docs.travis-ci.com/user/cron-jobs/) and running a different script if `TRAVIS_EVENT_TYPE` == `cron`.

**Comment by rbuffat** [comment]
The WMS bot checks now weekly for most WMS servers if they support EPSG:3857 even if they do not advertise it.
