### ISSUE TITLE
Linter improvements

### ISSUE THREAD

**Issue by grischard** [osmlab/editor-layer-index#428]
The QA of the current sources would be made easier if we had a better test suite than our current `make check`. #425  is an excellent addition, #211 would be great.

In addition to those, it would be good if we could easily check sources for missing attributes, and for a layer's presence in [JOSM's ImageryCompare](https://josm.openstreetmap.de/wiki/ImageryCompare).

Any other ideas?

- [x] Check for duplicate attributes
- [ ] Check whether layer is present in JOSM's [JOSM's ImageryCompare](https://josm.openstreetmap.de/wiki/ImageryCompare).
- [x] Check for missing attributes - do this in code or by tightening JSON Schema
   - [x] there should be an attribution
   - [x] for types that depend on it, there should be projections, min and max zooms
       - [x] but they shouldn't be present in places where they don't make sense, e.g. a tms with projections
   - [x] license should be present
- [ ] #211 Use GeoJSON linter to test geojson input
- [x] check for url arguments - a wms should have {proj}, a tms should have {x}, etc.
- [ ] check for useless redundant projections, like josm's ImageryCompare does
- [x] there should be a geometry and a country, unless the layer is global

**Checks that require making requests to the services**
- [ ] #425 Check for interesting EPSG:3857-like projections
- [ ] Check whether layer returns images at all - see all the borken layers #425 found
    - for wms we can just request the bbox
    - for tms [maybe this?](https://gist.github.com/tucotuco/1193577)
- [ ] Check whether http resources are also available over https
- [ ] Check whether max_zoom+1 or min_zoom-1 return images
- [ ] Check whether trailing slashes and www prefixes can be removed

**Comment by Marc-marc-marc** [comment]
also check for duplicate attribute like https://github.com/osmlab/editor-layer-index/commit/02ae97a259ca6f17c4ba50565424a70d7e75cb6d

**Comment by grischard** [comment]
Unfortunately, we can't use json schema to check for duplicate attributes. @handrews from the JSON schema project very kindly took the time to explain this to me.

Presumably to avoid requiring parsers to keep track of which properties they've already seen, JSON allows this redefinition, but states that the resulting behavior is undefined. The most common behaviour is to parse JSON objects into data structures with unique keys.  So by the time JSON Schema sees the data, the parser has already decided whether to raise an error, or just silently drop one or the other property definition.

JSON Schema can't tell what has happened, as JSON Schema does not consider the original input text.  So there is no way to constrain this in JSON Schema.

Instead, I will hook the data structure that json.load parses into a function that checks for duplicate keys.

**Comment by grischard** [comment]
Some thoughts on what extra attributes to check for:

- license should be compulsory
- for types that depend on it, there should be projections, min and max zooms, 
- there should be a boundary bbox and geometry, unless default is true (that last part is more complicated)

**Comment by rbuffat** [comment]
With the exception of 
- Check whether layer is present in JOSM's [JOSM's ImageryCompare](https://josm.openstreetmap.de/wiki/ImageryCompare).
- Check whether trailing slashes and www prefixes can be removed

I think everything of the list above is implemented either in `check.py` (Testing the "minimal" checks for all sources without HTTP requests), `strict_check.py` (Stricter checks for all new or changed sources including HTTP requests), and  https://rbuffat.github.io/eli_watchdog (Daily checks if the imagery is still alive).

Also as this issue is quite old and the last update was 4 years ago I'm closing this issue. @grischard  If you feel otherwise please reopen it again!

**Comment by grischard** [comment]
The slashes and prefix are quite minor, but synchronisation with josm is probably so big that it could use its own ticket.

**Comment by rbuffat** [comment]
> The slashes and prefix are quite minor, but synchronisation with josm is probably so big that it could use its own ticket.

True! I don't think that an automatic import from JOSM data is a good idea. Not sure what the best way would be. Maybe a https://josm.openstreetmap.de/wiki/ImageryCompare like script with the focus of only the most important things (changed license URLs / changed imagery URLs, and missing imagery)

**Comment by grischard** [comment]
The focus, long term, should be to have one index. Easy conversions and things like automatic PRs to reflect in ELI what's been updated on the JOSM side would make our lives a lot easier.

It's something where I'm hoping @tyrasd will have some good ideas.

**Comment by rbuffat** [comment]
> Easy conversions and things like automatic PRs to reflect in ELI what's been updated on the JOSM side would make our lives a lot easier.

I'm strongly against such automatic imports without review. Everybody can enter anything in the JOSM index. The system here where in most cases a second person has a look at the license terms is something that should not be abandoned.

If something is in the index the chances that somebody else will look at it is slim. https://github.com/osmlab/editor-layer-index/labels/waitfor%20-%20license%20%2F%20usage%20permission shows that it is good to have a second person look at it.
